config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers =>  { registrations: 'registrations'}
  resources :posts
  resources :users
  resources :comments

  post '/request_follow' => 'users#request_follow', as: "request_follow"
  post '/follow' => 'users#follow', as: 'follow'
  post '/reject_friendship' => 'users#reject_friendship', as: 'reject_friendship'
  post '/like_post' => 'users#like_post', as: 'like_post'
  get '/you_page' => 'users#you_page', as: "you_page"
  get '/friend_page' => 'posts#friend_page', as: "friend_page"

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :liker, class_name: "User"
    belongs_to :liked_post, class_name: "Post"
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :author, class_name: "User"
    has_many :comments

    has_many :likes, foreign_key: "liked_post_id"
    has_many :likers, through: :likes
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]

  has_attached_file :profile_picture, styles: {thumb: "50x50>"}, default_url: "https://t3.ftcdn.net/jpg/00/64/67/52/240_F_64675209_7ve2XQANuzuHjMZXP3aIYIpsDKEbF5dD.jpg"
  validates_attachment_content_type :profile_picture, content_type: /\Aimage\/.*\z/

  has_many :posts, foreign_key: "author_id", :dependent => :destroy
  
  has_many :user_requests
  has_many :friendships

  has_many :comments

  has_many :likes, foreign_key: "liker_id"
  has_many :liked_posts, through: :likes, source: :liked_post

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_message(self).deliver_now
    redirect_to posts_path
  end
end

app/models/user_request.rb
class UserRequest < ApplicationRecord
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @comment = current_user.comments.new(comment_params)

        if @comment.save
            flash[:message] = "comment posted"
        else
            flash[:message] = "comment could not be posted"
        end

        redirect_to post_path(@comment.post.id)
    end

    private

    def comment_params
        params.require(:comment).permit(:body, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    def index
        @posts = Post.all.order(created_at: :desc)
    end

    def friend_page
        @posts = Post.all.order(created_at: :desc)
    end

    def new
        @post = current_user.posts.build
    end 

    def show
        @post = Post.find(params[:id])
        @comment = Comment.new
        @author = @post.author
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = current_user.posts.update(posts_params)
        redirect_to post_path(@post)
    end

    def create
        @post = current_user.posts.build(posts_params)
        p = @post.errors.messages
        if @post.save 
            redirect_to root_path
        else
            redirect_to new_post_path
        end
    end 

    private
    def posts_params
        params.require(:post).permit(:body)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
    def sign_up_params
        params.require(:user).permit(:username, :email, :profile_picture, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :email, :profile_picture, :password, :password_confirmation, :current_password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
    end

    def request_follow
        @user = User.find(params[:user_id])
        @user.user_requests.create(requester_id: params[:requester_id])

        redirect_back(fallback_location: root_path)
    end

    def reject_friendship
        @user = User.find(params[:user_id])
        @user.user_requests.find_by(requester_id: params[:friend_id]).destroy

        redirect_back(fallback_location: root_path)
    end

    def like_post
        @user = User.find(current_user.id)
        @user.liked_posts << Post.find(params[:post_id])
        @user.save

        redirect_back(fallback_location: root_path)
        
    end
    
    def follow 
        @user = User.find(params[:user_id])
        @friend = User.find(params[:friend_id])

        @user.friendships.create(friend_id: @friend.id)
        @friend.friendships.create(friend_id: @user.id)
        @user.user_requests.find_by(requester_id: @friend.id).destroy
        
        redirect_back(fallback_location: root_path)

    end 


    def you_page 
        @user = User.find(current_user.id)
        @requests = UserRequest.all
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@600&display=swap" rel="stylesheet"> 
<!DOCTYPE html>
<html>
  <head>
    <%= flash[:message] %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <title>Facepalm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <nav class="options">
      <div class="positioning">
        <div class="facepalm-logo"><h2>facepalm</h2></div>
        <% if !user_signed_in?%>
          <div class="nav-object"><%= link_to 'sign_up', new_user_registration_path %>
          <%= link_to 'sign_in', new_user_session_path %>
          <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
        <% end %>
        <%= link_to 'home', root_path %>
        <%= link_to 'new_post', new_post_path %>
        <% if user_signed_in?%>
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
          <%= link_to "timeline", friend_page_path%>
          <%= link_to "My Page", you_page_path%>
          friend requests <%= current_user.user_requests.count%>
        <% end %>
      </div>
    </nav>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= link_to 'all users', users_path%>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |post|%>
    <div class=""><%= post.label "post contents: " %></div> 
    <div class=""><%= post.text_area :body %></div>
    <div class=""><%= post.submit "post" %></div>
<% end %>

app/views/posts/_likes.html.erb
<% if @post.likers.present? &&  user_signed_in? %>
    <% if !@post.likers.where(id: current_user.id).present? %>
        <%= form_with(url: like_post_path) do %>
            <%= hidden_field_tag :post_id, @post.id%>
            <%= submit_tag 'Like Post'%>
        <% end %>
    <% end %>
<% elsif user_signed_in? %>
    <%= form_with(url: like_post_path) do %>
        <%= hidden_field_tag :post_id, @post.id%>
        <%= submit_tag 'Like Post'%>
    <% end %>
<% end %>

app/views/posts/_post_info.html.erb
<div class="post">
    <div class="post-contents">
        <div class="post-author">author: <%= post.author.username%></div>
        <br>
        <div class="post-body"><%= post.body%></div>
        <div class="post-options">
        <%= link_to 'view post', post_path(post)%> 
            <% if user_signed_in? %>
                <% if current_user.id == post.author.id %>
                    <%= link_to 'edit post', edit_post_path(post)%>
                <% end %>
            <% end %>
            <br>
        </div>
     </div>
</div>

app/views/posts/edit.html.erb
<h2>edit post</h2>

<%= render :partial => 'form'%>

app/views/posts/friend_page.html.erb
<h2>timeline</h2>

<% @posts.each do |post|%>
    <% post.author.friendships.each do |friend| %>
        <% if friend.friend_id == current_user.id || friend.user_id == current_user.id %>
            <%= render :partial => 'post_info', :locals => {post: post} %>
            <% break %>
        <% end %>
    <% end %>
<% end %>

app/views/posts/index.html.erb
<div class="home-page">
    
<div class="post-title"><h3>posts </h3></div>
    <% if @posts.present? %>
        <% @posts.each do |post|%>
            <%= render :partial => 'post_info', locals: {post: post}%>
        <% end %>
    <% end %>

</div>

app/views/posts/new.html.erb
<h2>new post</h2>

<%= render :partial => 'form'%>

app/views/posts/show.html.erb
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" /><meta http-equiv="Expires" content="0" />

<div class="post-owner">
    <h3>username: <%= @author.username%> <br>email: <%= @author.email%></h3>
</div>
<p>post:
    <div class="post-contents"><%= @post.body%></div>
<p>
<p>likes: <%= @post.likers.count%></p>

<%= render :partial => 'likes'%>

<h2>comments</h2>
<% if @post.comments.present? %>
    <% @post.comments.each do |comment| %>
        <p><%= User.find(comment.user_id).username %></p>
        <p><%= comment.body %></p>
    <% end %>
<% else %>
    <p> there are no comments </p>
<% end %>

<% if @author == current_user%>
    <h3><%= link_to 'view', you_page_path %> your page </h3>
<% else %>
    <h3><%= link_to 'view', user_path(@author) %> <%= @author.username%>'s page</h3>
<% end %>

<%= form_with model: @comment, local: true do |comment| %>
    <%= comment.text_field :body%>
    <%= comment.hidden_field :post_id, :value => @post.id %>
    <%= comment.submit "comment on post"%>
<% end %>

app/views/users/_follow.html.erb
<% if current_user != @user && user_signed_in? %>
    <div class="follow-request-form">
        <% if @user.user_requests.find_by(requester_id: current_user.id).present? %>
            <p>request pending</p>
        <% elsif @user.friendships.find_by(friend_id: current_user.id).present? %>
            friends
        <% else %>
            <div class="follow-form">
                <%= form_with(url: request_follow_path) do %>
                    <%= hidden_field_tag(:user_id, @user.id)%>
                    <%= hidden_field_tag(:requester_id, current_user.id)%>
                    <%= submit_tag "follow #{@user.username}"%>
                <% end %>
            </div>
        <% end %>
    </div>
<% end %>

app/views/users/_friend_requests.html.erb
<% if @user.user_requests.present? %>
    <% @user.user_requests.each do |requests|%>
        <p>
            <% @friend = User.find(requests.requester_id) %> 
            <%= @friend.username%> wants to follow you
            <%= form_with(url: follow_path) do %>
                    <% @friend = User.find(requests.requester_id) %> 
                    <%= hidden_field_tag :friend_id, @friend.id%>
                    <%= hidden_field_tag :user_id, @user.id%>
                    <%= submit_tag "accept"%>
            <% end %>
            <%= form_with(url: reject_friendship_path) do %>
                    <%= hidden_field_tag :friend_id, @friend.id%>
                    <%= hidden_field_tag :user_id, @user.id%>
                    <%= submit_tag "decline"%>
            <% end %>
        </p>
    <% end %>
<% else %>
    <p>you currently have no friends requests </p>
<% end %>

app/views/users/_friends.html.erb
<%if @user.friendships.present? %>
    <% @user.friendships.each do |friend|%>
        <p><%= User.find(friend.friend_id).username%></p>
    <% end %>
<% else %>
    <p>you currently have no friends</p>
<% end %>

app/views/users/_pending_requests.html.erb
<% if @requests.present? %>
    <% @request_list = []%>
    <% @requests.each do |request| %>
        <% if request.requester_id == @user.id %>
            <p><%= User.find(request.user_id).username %></p>
            <% @request_list << User.find(request.user_id).username %>
        <% end %>
    <% end %>
    <% if !@request_list.present?%>
        <p>you have no pending friend requests</p>
    <% end %>
<% end %>

app/views/users/_user_page.html.erb
<%= render :partial => 'follow'%>

<h2>Personal Info</h2>
<div class="personal-info" id="user-info">
    <h3><div class="profile-picture"><%= image_tag @user.profile_picture.url(:thumb), :size => "50x50"%></div> </h3>
    <h3>username: <%= @user.username%> </h3>
    <h3>email: <%= @user.email%></h3>
    <h3>post count: <%= @user.posts.count%></h3>
</div>
<% if user_signed_in?%>
    <% if current_user.id == @user.id%>
        <%= link_to 'edit your profile', edit_user_registration_path %>
    <% end %>
<% end %>

<h2>post history:</h2>
<% if @user.posts.present?%>
    <div class="post-history" id="user-info">
        <% @user.posts.each do |post|%>
            <div class="post-body">
                <p><%= post.body %></p>
            </div>
        <% end %>
    </div>

<% else %>
    <p>you have not made any posts yet, you can do so <%= link_to 'here', new_post_path%></p>
<% end %>

app/views/users/index.html.erb
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" /><meta http-equiv="Expires" content="0" />

<h1>All Users</h1>

<h2>Requested/Potential Friends</h2>
<div id="user-info">
    <% @users.each do |user|%>
        <% if current_user.friendships.where(friend_id: user.id).present?%>
            <% next %>
        <% end %>

        <% if user_signed_in? %>
            <% if user.id != current_user.id %>
                <% @user = user %>
                <h3><%= user.username %>'s status: </h3> <p class="r-p"><%= render :partial => 'follow'%></p>
            <% end %>
        <% end %>
    <% end %>
</div>

<h2>Friends</h2>
<div id="user-info">
    <% @user = current_user %>
    <h3><%= render :partial => 'friends'%></h3>
</div>

app/views/users/show.html.erb
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" /><meta http-equiv="Expires" content="0" />
<h1>user info</h1>

<%= render :partial => 'user_page'%>

app/views/users/you_page.html.erb
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" /><meta http-equiv="Expires" content="0" />

<h2>My Page</h2>

<h2>upload profile picture</h2>

<%= render :partial => 'user_page'%>

<h2>Friendship Details</h2>

<div class="friendship-details">
    <div class="friendship-content">

        <h3>Friends</h3>
        <%= render :partial => 'friends'%>

        <h3>Friend Requests</h3>
        <%= render :partial => 'friend_requests'%>

        <h3>Pending Friend Requests</h3>
        <%= render :partial => 'pending_requests'%>
        
    </div>
</div>